### ISSUE TITLE
Question about how Vuex actions are constructed

### ISSUE THREAD

**Issue by pyrello** [mattjdev/cloudbudget#1]
Considering the following code block:

``` javascript
export const transactionsActions = {
  ...
  getTransactions({ dispatch }) {
    return new Promise((resolve) => {
      Vue.http.get('transactions')
        .then((response) => {
          dispatch(SET_TRANSACTIONS, response.data.data);
          const deadTransactions = _.differenceBy(transactionsState.transactions, response.data.data, 'id');
          dispatch(REMOVE_TRANSACTIONS, deadTransactions);
          resolve(response.data.data);
        })
        .catch((response) => {
          resolve(response.data.errors);
        });
    });
  },
}
```

Your getTransactions() function explicitly returns a Promise as a wrapper for the result of a vue resource request. But, in this case, Vue.http.get() returns a Promise as it's result. Why do you add the extra Promise wrapper around it?

**Comment by codingmatty** [comment]
I'm not sure if this is the _correct_ way to do it, but I believe the reason I did this was to place the responsibility of dispatching the actions within this code, instead of expected the code calling `getTransactions` to do the dispatching of actions. And the actions being dispatched are really just to set/modify the state on the client based on what the server returns from the http call.

**Comment by codingmatty** [comment]
I also just realized that I could just return the promise with a chained then like "return http.get().then()" doing all of the dispatching in the then statement.

**Comment by pyrello** [comment]
Thanks for the response. I wasn't sure if the `resolve(response.data.data)` was important for some reason. I did a little bit of testing on this and I have found that the following code seems to work pretty much the same:

``` javascript
export const transactionsActions = {
  ...
  getTransactions({ dispatch }) {
    return Vue.http.get('transactions')
        .then((response) => {
          dispatch(SET_TRANSACTIONS, response.data.data);
          const deadTransactions = _.differenceBy(transactionsState.transactions, response.data.data, 'id');
          dispatch(REMOVE_TRANSACTIONS, deadTransactions);
        })
        .catch((response) => {
          // handle error
        });
  },
}
```

**Comment by codingmatty** [comment]
Yea, makes sense. I haven't played with this app in awhile, so that's probably a better solution.

**Comment by pyrello** [comment]
No worries. I was using this project as a starting point for understanding the application layout for using Vue, Vue Router, Vue Resource, and Vuex. Thanks for taking the time to answer my question.
